services:
  - type: web
    name: mastertech-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb://mtiuser:MtiPass123!@ac-thlzd0c-shard-00-00.ayq9k3f.mongodb.net:27017,ac-thlzd0c-shard-00-01.ayq9k3f.mongodb.net:27017,ac-thlzd0c-shard-00-02.ayq9k3f.mongodb.net:27017/mti-projects?ssl=true&replicaSet=atlas-s9yn0c-shard-0&authSource=admin&retryWrites=true&w=majority&appName=mti-cluster
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: "1111"
      - key: SESSION_SECRET
        value: ${SESSION_SECRET}
      - key: EMAIL_USER
        value: ${EMAIL_USER}
      - key: EMAIL_PASS
        value: ${EMAIL_PASS}
      - key: CONTACT_EMAIL
        value: ${CONTACT_EMAIL}

  - type: web
    name: mastertech-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: ${REACT_APP_API_URL}
