services:
  - type: web
    name: mastertech-backend
    env: node
    rootDir: backend
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: ADMIN_USER
        value: ${ADMIN_USER}
      - key: ADMIN_PASS
        value: ${ADMIN_PASS}
      - key: SESSION_SECRET
        value: ${SESSION_SECRET}
      - key: EMAIL_USER
        value: ${EMAIL_USER}
      - key: EMAIL_PASS
        value: ${EMAIL_PASS}
      - key: CONTACT_EMAIL
        value: ${CONTACT_EMAIL}

  - type: web
    name: mastertech-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: ${REACT_APP_API_URL}
